version: "3"
services:
  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 6379:6379
    networks: 
      - scrapy_network
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    environment:
     - MONGO_DATA_DIR=/usr/var/db
     - MONGO_LOG_DIR=/dev/null
    ports:
     - 27017:27017
    networks: 
      - scrapy_network
  app:
    build: .
    container_name: "app"
    command: ./run.sh
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - celery
      - mongodb
    links:
      - mongodb
    networks: 
      - scrapy_network
    stdin_open: true
    tty: true
  celery:
    build: .
    container_name: "celery"
    command: celery -A scrapy_api.celery.app worker --loglevel=debug
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - mongodb
    links:
      - redis
      - mongodb
    networks: 
      - scrapy_network
networks:
  scrapy_network:
    external: false

