version: "3"
services:
  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 6379:6379
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    environment:
     - MONGO_DATA_DIR=/usr/var/db
     - MONGO_LOG_DIR=/dev/null
    ports:
     - 27017:27017
  app:
    build: .
    container_name: "app"
    command: pipenv run gunicorn
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - celery
      - mongodb
    links:
      - mongodb
    stdin_open: true
    tty: true
  celery:
    build: .
    container_name: "celery"
    command: pipenv run celery
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - mongodb
    links:
      - redis
      - mongodb

