default:
  app_version: 1.0-dev
  app_name: Scrapy API
  app_descr: 'REST API for parsing data information from websites.'
development:
  DEBUG: true
  MONGODB_DB: "scrapy_db"
  MONGODB_HOST: "localhost"
  MONGODB_PORT: 27017
  CELERY_BROKER_URL: "redis://localhost:6379/0"
  CELERY_RESULT_BACKEND: "redis://localhost:6379/0"
testing:
  DEBUG: true
  MONGODB_DB: "scrapy_db"
  MONGODB_HOST: "mongodb"
  MONGODB_PORT: 27017
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
production:
  DEBUG: false
  MONGODB_DB: "scrapy_db"
  MONGODB_HOST: "mongodb"
  MONGODB_PORT: 27017
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  